Dataclass for simple RNTuple test files (#39)
* Dataclass for simple RNTuple test files
Fixes #29

* update representation, need to fix bug w/ _unknown field

* initial lint (still have error: Unexpected keyword argument "_unknown" for "SchemaExtension")

* fix _unknown compare bug

* remove rntuple reader (debugger)

* remove reference to rntuple_reader in ruff lint

* Disable fCountClass check for now

---------

Co-authored-by: Nick Smith <nick.smith@cern.ch>